name: postman-pull-push-requests

on: [push,pull_request,workflow_dispatch] 

jobs:
    test-api:
        runs-on: ubuntu-latest
        steps:
          - name: Check out Git repository
            uses: actions/checkout@master
          - name: Install node js
            uses: actions/setup-node@v1
            with:
                node-version: '12.x'
        
          - name: install newman
            run: npm install -g newman
          
          - name: rum collections
            run: |
                newman run ./Simple_Book_API.postman_collection.json
